language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install boto3==1.6.22
  - pip install Flask
  - pip install moto==1.3.1
  - pip install coveralls

before_script:
  - moto_server s3 &
  - sleep 10

script:
  - coverage run tests.py

after_success:
  - codecov