language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install boto3==1.6.22
  - pip install moto==1.3.1
  - pip install coveralls

script:
  - coverage run tests.py

after_success:
  - codecov